import { eq } from "drizzle-orm";
import { withTenant } from "@/db/client";
import { curriculumModules, organisations, qualifications } from "@/db/schema";
import { recordAudit } from "./audit";
import {
  aliasTable,
  aliasesFrom,
  normaliseCode,
  type AliasRow,
  type CodeAliases,
} from "./module-codes";
import { assertSessionCan, type AuthenticatedSession } from "./session";

/**
 * A tenant's module code table: reading it, proposing it, storing it.
 *
 * The permutation rules are in lib/module-codes.ts, which imports nothing so
 * the settings modal can run them live in the browser. This half reaches the
 * database and so must never be imported by a client component.
 *
 * Roland, 21 September: "Once a code is selected under settings, let the
 * system create permutations and display them in a modal window so that the
 * user can alter, add others, and confirm them. Then the system can use these
 * when uploading."
 *
 * The confirmation is the point and not a formality. These are generated by a
 * rule, and a rule that is wrong about a provider's documents is wrong
 * fifteen times at once and invisibly - a module quietly matched to the wrong
 * one links a learner's evidence to the wrong half of a curriculum with
 * nothing on any screen looking amiss. So nothing is used until a person has
 * looked at it, and what was withheld is shown beside what was kept.
 */

export class ModuleCodeError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ModuleCodeError";
  }
}

/** The table in force. Empty until somebody has confirmed one. */
export async function moduleCodeAliasesFor(
  session: AuthenticatedSession,
): Promise<CodeAliases> {
  return withTenant(session.organisationId, async (tx) => {
    const [organisation] = await tx
      .select({ aliases: organisations.moduleCodeAliases })
      .from(organisations)
      .where(eq(organisations.id, session.organisationId));

    return organisation?.aliases ?? {};
  });
}

/**
 * Every module code this tenant actually uses, across every qualification.
 *
 * The table is the tenant's rather than one qualification's, because the
 * documents it exists to read are the tenant's: a workbook filename written
 * one way is written that way across their whole catalogue. Codes are
 * collected from what is loaded rather than declared, so the proposal is about
 * this provider's real curriculum and not a scheme somebody typed.
 */
export async function moduleCodesInUse(
  session: AuthenticatedSession,
): Promise<string[]> {
  assertSessionCan(session, "course:read");

  return withTenant(session.organisationId, async (tx) => {
    const rows = await tx
      .select({ code: curriculumModules.code })
      .from(curriculumModules)
      .innerJoin(
        qualifications,
        eq(qualifications.id, curriculumModules.qualificationId),
      )
      .where(eq(qualifications.organisationId, session.organisationId));

    return [...new Set(rows.map((row) => normaliseCode(row.code)))]
      .filter(Boolean)
      .sort((a, b) => a.localeCompare(b));
  });
}

export type ProposedTable = {
  rows: AliasRow[];
  /** What is stored now, so the screen can show confirmed against proposed. */
  stored: CodeAliases;
  /** True once somebody has confirmed a table. */
  confirmed: boolean;
};

/**
 * What the platform would propose, beside what is in force.
 *
 * Proposing on every read rather than storing a proposal: the curriculum
 * changes as qualifications are loaded, and a proposal frozen at the moment
 * the feature was first opened would go stale without anybody being told. A
 * row already confirmed keeps its stored spellings; a module loaded since is
 * proposed fresh.
 */
export async function proposeModuleCodeTable(
  session: AuthenticatedSession,
): Promise<ProposedTable> {
  assertSessionCan(session, "tenant:manage_settings");

  const [codes, stored] = await Promise.all([
    moduleCodesInUse(session),
    moduleCodeAliasesFor(session),
  ]);

  const generated = aliasTable(codes);

  const rows = generated.map((row) => {
    const held = stored[row.canonical];
    if (!held) return row;

    /*
     * A confirmed row wins, including where somebody removed a spelling the
     * generator still proposes. Re-adding it on every visit would undo the
     * edit silently and repeatedly, which is worse than never proposing it.
     */
    return { ...row, aliases: held.map(normaliseCode).filter(Boolean) };
  });

  return { rows, stored, confirmed: Object.keys(stored).length > 0 };
}

/**
 * Stores a table somebody has looked at.
 *
 * Checked rather than trusted, because this arrives from a form and decides
 * what matches what. Two rules, and both exist to stop a table doing harm no
 * screen would show:
 *
 *   An alias may not be a module code. The resolver checks exact matches
 *   first, so such an alias could never win - but it would sit in the table
 *   looking as though it does, and somebody would eventually rely on it.
 *
 *   An alias may not be claimed by two modules. That is the ambiguity the
 *   generator refuses, and a person editing by hand must be held to it too:
 *   the whole failure mode is a knowledge module matching a workplace one.
 */
export async function setModuleCodeAliases(
  session: AuthenticatedSession,
  table: CodeAliases,
): Promise<CodeAliases> {
  assertSessionCan(session, "tenant:manage_settings");

  const cleaned: CodeAliases = {};

  /*
   * Checked against every module this tenant holds, not merely the rows that
   * happened to be submitted.
   *
   * Built from the submitted keys alone, this let { KM01: ["PM01"] } through:
   * PM01 is a real module, but it was not a key in that payload, so nothing
   * recognised it. The form always posts the whole table, which is exactly why
   * the check must not depend on the form - a partial payload is the shape a
   * mistake or a crafted request takes, and it is the shape the rule has to
   * hold for. Found by a test written against a live curriculum rather than
   * against the form's own habits.
   */
  const canonicals = new Set([
    ...(await moduleCodesInUse(session)),
    ...Object.keys(table).map(normaliseCode).filter(Boolean),
  ]);
  const claimedBy = new Map<string, string>();

  for (const [rawCanonical, rawAliases] of Object.entries(table)) {
    const canonical = normaliseCode(rawCanonical);
    if (!canonical) continue;

    const accepted: string[] = [];

    for (const rawAlias of rawAliases) {
      const alias = normaliseCode(rawAlias);
      if (!alias || alias === canonical) continue;

      if (canonicals.has(alias)) {
        throw new ModuleCodeError(
          `${alias} is a module code of its own, so it cannot also be another spelling of ${canonical}. Remove it from ${canonical}.`,
        );
      }

      const already = claimedBy.get(alias);
      if (already && already !== canonical) {
        throw new ModuleCodeError(
          `${alias} is listed under both ${already} and ${canonical}. A spelling can only mean one module — remove it from one of them.`,
        );
      }

      claimedBy.set(alias, canonical);
      if (!accepted.includes(alias)) accepted.push(alias);
    }

    if (accepted.length > 0) cleaned[canonical] = accepted.sort();
  }

  return withTenant(session.organisationId, async (tx) => {
    const [before] = await tx
      .select({ aliases: organisations.moduleCodeAliases })
      .from(organisations)
      .where(eq(organisations.id, session.organisationId));

    await tx
      .update(organisations)
      .set({ moduleCodeAliases: cleaned })
      .where(eq(organisations.id, session.organisationId));

    await recordAudit(tx, {
      organisationId: session.organisationId,
      actorId: session.userId,
      action: "module_code_aliases.set",
      entityType: "organisation",
      entityId: session.organisationId,
      before: { aliases: before?.aliases ?? null },
      after: { aliases: cleaned },
    });

    return cleaned;
  });
}

/** The generated table, for a caller that wants it without the stored one. */
export { aliasTable, aliasesFrom };
