#!/usr/bin/env bash
#
# Sets up a fresh Linux server to run the ROFT LMS.
#
# Installs Docker, opens the firewall, generates secrets, brings the stack up,
# creates the schema and applies the security policies.
#
#   curl -fsSL https://raw.githubusercontent.com/Rolbaron001/roft-lms/main/scripts/bootstrap-server.sh -o bootstrap.sh
#   bash bootstrap.sh lms.roftbusiness.org you@roftbusiness.org
#
# Safe to run again: every step checks before acting, so a run that stopped
# half way can simply be repeated.
#
# It does NOT touch the Oracle Cloud console. The Security List still has to
# allow ports 80 and 443 — the script says so at the end, because forgetting
# it is the usual reason a new instance looks dead.

set -Eeuo pipefail

DOMAIN="${1:-}"
EMAIL="${2:-}"
REPO="${REPO:-https://github.com/Rolbaron001/roft-lms.git}"
APP_DIR="${APP_DIR:-$HOME/roft-lms}"

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
note() { printf '    %s\n' "$*"; }
die()  { printf '\n\033[31mStopped: %s\033[0m\n\n' "$*" >&2; exit 1; }

trap 'die "step failed at line $LINENO. Nothing further was changed."' ERR

[[ -n "$DOMAIN" ]] || die "Give the domain, e.g.: bash bootstrap.sh lms.roftbusiness.org you@roftbusiness.org"
[[ -n "$EMAIL"  ]] || die "Give an email address for certificate notices."
[[ $EUID -ne 0  ]] || die "Run as your normal user, not root. It will use sudo where needed."

say "Setting up ${DOMAIN}"
note "Architecture: $(uname -m)"
note "User:         $(whoami)"

# ---------------------------------------------------------------- packages
say "Installing what is needed"

if command -v apt-get >/dev/null 2>&1; then
  PKG=apt
  sudo apt-get update -qq
  sudo apt-get install -y -qq \
    docker.io docker-compose-v2 git postgresql-client curl ca-certificates
elif command -v dnf >/dev/null 2>&1; then
  # Oracle Linux, the default image on Oracle Cloud.
  PKG=dnf
  sudo dnf install -y -q dnf-utils git postgresql curl ca-certificates
  if ! command -v docker >/dev/null 2>&1; then
    sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo dnf install -y -q docker-ce docker-ce-cli containerd.io docker-compose-plugin
  fi
  sudo systemctl enable --now docker
else
  die "Unrecognised Linux. This expects Ubuntu or Oracle Linux."
fi

if ! groups | grep -qw docker; then
  sudo usermod -aG docker "$USER"
  DOCKER_GROUP_ADDED=yes
fi

note "Docker: $(sudo docker --version 2>/dev/null || echo 'not responding yet')"

# ---------------------------------------------------------------- firewall
say "Opening ports 80 and 443 on the machine"

if command -v firewall-cmd >/dev/null 2>&1 && sudo firewall-cmd --state >/dev/null 2>&1; then
  sudo firewall-cmd --permanent --add-service=http  >/dev/null
  sudo firewall-cmd --permanent --add-service=https >/dev/null
  sudo firewall-cmd --reload >/dev/null
  note "firewalld updated."
else
  # Oracle Linux images also ship iptables rules that reject everything else.
  sudo iptables -I INPUT -p tcp --dport 80  -j ACCEPT || true
  sudo iptables -I INPUT -p tcp --dport 443 -j ACCEPT || true
  if command -v netfilter-persistent >/dev/null 2>&1; then
    sudo netfilter-persistent save >/dev/null
  elif [[ -d /etc/iptables ]]; then
    sudo sh -c 'iptables-save > /etc/iptables/rules.v4'
  fi
  note "iptables updated."
fi

# ------------------------------------------------------------------- code
say "Fetching the application"

if [[ -d "$APP_DIR/.git" ]]; then
  git -C "$APP_DIR" pull --ff-only
  note "Updated existing copy at ${APP_DIR}"
else
  git clone --quiet "$REPO" "$APP_DIR"
  note "Cloned into ${APP_DIR}"
fi

cd "$APP_DIR"

# ---------------------------------------------------------------- secrets
say "Settings and secrets"

if [[ -f .env ]]; then
  note ".env already exists — leaving it exactly as it is."
  note "Delete it and run again only if you want new secrets."
else
  gen() { openssl rand -base64 36 | tr -d '\n/+=' | cut -c1-40; }

  POSTGRES_PASSWORD="$(gen)"
  ROFT_APP_DB_PASSWORD="$(gen)"
  AUTH_SECRET="$(openssl rand -base64 32)"
  BACKUP_PASSPHRASE="$(gen)$(gen)"

  # One settings file. Backups run inside the tools container, which is on the
  # internal network — the database has no published port, so the host has no
  # route to it and a host-run backup script could not connect.
  cat > .env <<ENVFILE
# Generated by bootstrap-server.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
LMS_DOMAIN=${DOMAIN}
LMS_TLS_EMAIL=${EMAIL}

POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=roft_lms
ROFT_APP_DB_PASSWORD=${ROFT_APP_DB_PASSWORD}

AUTH_SECRET=${AUTH_SECRET}

# Backups. Fill in the bucket once object storage exists; until then run the
# backup with --local-only and the files stay in ./backups.
BACKUP_PASSPHRASE=${BACKUP_PASSPHRASE}
BACKUP_BUCKET=
BACKUP_S3_ENDPOINT=

# Email. Until these are set, notifications queue rather than being sent.
MAIL_HOST=
MAIL_PORT=587
MAIL_USER=
MAIL_PASSWORD=
MAIL_FROM=
ENVFILE
  chmod 600 .env

  mkdir -p backups

  # Printed once, deliberately. Without it every backup is unreadable, and it
  # must not live only on the machine the backups protect.
  printf '\n\033[33m'
  printf '  ────────────────────────────────────────────────────────────\n'
  printf '   WRITE THIS DOWN NOW, SOMEWHERE THAT IS NOT THIS SERVER\n\n'
  printf '   Backup passphrase:\n   %s\n\n' "$BACKUP_PASSPHRASE"
  printf '   Every backup is encrypted with it. Lose it and the backups\n'
  printf '   are permanently unreadable, which defeats having them.\n'
  printf '   A password manager, not a note on this machine.\n'
  printf '  ────────────────────────────────────────────────────────────\n'
  printf '\033[0m\n'

  read -r -p "   Saved it? Type YES to continue: " CONFIRMED
  [[ "$CONFIRMED" == "YES" ]] || die "Nothing was started. Run again when you have saved it."
fi

# ------------------------------------------------------------------ start
say "Building and starting (first build takes a few minutes)"

DC="sudo docker compose -f docker-compose.production.yml"
$DC up -d --build

say "Waiting for the database"
for _ in $(seq 1 60); do
  if $DC exec -T db pg_isready -U postgres -d roft_lms >/dev/null 2>&1; then
    note "Database is up."
    break
  fi
  sleep 2
done

# Through the tools container, not the app: the application image contains
# only the built app, with no drizzle-kit, tsx or scripts directory.
say "Creating the schema and applying the security policies"
$DC run --rm tools sh -c 'npx drizzle-kit push --force >/dev/null && npx tsx scripts/apply-policies.ts'

say "Loading the starting data"
$DC run --rm tools npx tsx scripts/seed.mts --if-empty --allow-remote

# ------------------------------------------------------------------ check
say "Checking it is answering"
sleep 3
if curl -fsS "http://127.0.0.1/api/health" -H "Host: ${DOMAIN}" >/dev/null 2>&1; then
  note "The application is responding."
else
  note "Not answering on the machine yet — check: ${DC} logs app"
fi

# Proving a backup restores before anything real is on the system is the
# cheapest time to find out it does not.
say "Taking a first backup and proving it restores"
if $DC run --rm tools ./scripts/backup.sh --local-only >/dev/null 2>&1; then
  if $DC run --rm tools sh -c \
    './scripts/restore.sh --verify $(ls -t /backups/*.dump.enc | head -1)' \
    2>&1 | grep -q "VERIFY PASSED"; then
    note "Backup taken and restore verified."
  else
    note "Backup taken but the restore check did not pass. Look into this."
  fi
else
  note "First backup did not run. Check: ${DC} run --rm tools ./scripts/backup.sh --local-only"
fi

# ------------------------------------------------------------------- done
cat <<DONE

$(printf '\033[1m')Done on this machine.$(printf '\033[0m')

Two things are outside this script and both are common stumbles:

  1. Oracle Cloud console → Networking → your VCN → Security List:
     allow inbound TCP 80 and 443 from 0.0.0.0/0.
     Without this the server is unreachable and looks broken.

  2. DNS: point both of these at this machine's public IP address

         ${DOMAIN}
         *.${DOMAIN}

     The wildcard is what lets a new client be added without touching DNS.

Certificates are requested automatically once DNS resolves here. If the site
does not come up, that is almost always the reason — wait, then check with:

    ${DC} logs caddy | tail -30

Then open:  https://${DOMAIN}

$(if [[ "${DOCKER_GROUP_ADDED:-no}" == "yes" ]]; then
  printf 'Log out and back in once, so you can run docker without sudo.\n\n'
fi)Everyday commands are in DEPLOY.md.
DONE
