/**
 * The phrases a browser can ask for. Job sheet D9.
 *
 *   npm run translations:client          rewrites lib/i18n/client-keys.ts
 *
 * A page rendered on the server has its words put in before it leaves; only
 * the parts that run in the browser (forms, menus, anything that changes as
 * somebody uses it) look phrases up there. Until 1 October every page carried
 * the reader's whole language with it, about 70 KB compressed on every page a
 * phone opened, for a little under half of it to be used. This lists what the
 * browser's own code can ask for, so `catalogueFor` sends only that.
 *
 * Read from the code that runs in the browser ("use client" files): every
 * string in it that is a phrase's key, and every key built from a template
 * (`session.kind.${kind}` is every key beginning `session.kind.`). A phrase it
 * misses is not lost: the browser holds the English and shows that.
 *
 * tests/client-phrases.test.ts fails when the list is behind the code.
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { en } from "../lib/i18n/en";

export const CLIENT_OUTPUT = join("lib", "i18n", "client-keys.ts");

function files(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      if (name !== "node_modules" && name !== ".next") files(full, out);
    } else if (/\.tsx?$/.test(name)) out.push(full);
  }
  return out;
}

/** The files that run in the browser. */
export function clientFiles(root = "."): string[] {
  return [...files(join(root, "app")), ...files(join(root, "components"))]
    .filter((path) => /^\s*["']use client["']/.test(readFileSync(path, "utf8")))
    .map((path) => relative(root, path).split(sep).join("/"))
    .sort();
}

export function clientPhrases(root = ".", catalogue: Record<string, string> = en) {
  const known = new Set(Object.keys(catalogue));
  const keys = new Set<string>();
  const prefixes = new Set<string>();
  for (const file of clientFiles(root)) {
    const source = readFileSync(join(root, file), "utf8");
    for (const match of source.matchAll(/["'`]([a-zA-Z][\w-]*(?:\.[\w./-]+)+)["'`]/g)) {
      if (known.has(match[1])) keys.add(match[1]);
    }
    for (const match of source.matchAll(/`([a-zA-Z][\w-]*\.[\w.-]*?)\$\{/g)) {
      const prefix = match[1];
      if ([...known].some((key) => key.startsWith(prefix))) prefixes.add(prefix);
    }
  }
  return { keys: [...keys].sort(), prefixes: [...prefixes].sort() };
}

export function renderClientKeys({ keys, prefixes }: { keys: string[]; prefixes: string[] }): string {
  return [
    "/**",
    " * The phrases a browser can ask for. Job sheet D9.",
    " *",
    " * Generated by `npm run translations:client` from the code that runs in the",
    " * browser: do not edit by hand. See scripts/client-phrases.ts.",
    " */",
    "export const CLIENT_KEYS: readonly string[] = [",
    ...keys.map((key) => `  ${JSON.stringify(key)},`),
    "];",
    "",
    "/** Keys the browser builds from a template: every key beginning with one of these. */",
    "export const CLIENT_PREFIXES: readonly string[] = [",
    ...prefixes.map((prefix) => `  ${JSON.stringify(prefix)},`),
    "];",
    "",
  ].join("\n");
}
